spring:
  datasource:
    url: jdbc:h2:mem:coindeskdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 2025coin08desk23db
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  sql:
#    init:
#      mode: never
